{ "a" : "T", "q" : "Una vaca puede subir escaleras pero no puede bajarlas." },
{ "a" : "T", "q" : "La comida que cae al suelo no se contamina si se recoge antes de 5 segundos." },
{ "a" : "T", "q" : "El ojo del avestruz es mas grande que su cerebro." },
{ "a" : "T", "q" : "El estadounidense Charles Osborne tuvo hipo durante 69 años." },
{ "a" : "T", "q" : "Los peces nunca tienen sed." },
{ "a" : "T", "q" : "El oso polar tiene la piel negra." },
{ "a" : "T", "q" : "El nombre completo de Picasso era: Pablo Diego José Francisco de Paula Juan Nepomuceno María de los Remedios Cipriano de la Santísima Trinidad Ruiz y Picasso." },
{ "a" : "T", "q" : "El animal marino más rápido es el delfín." },
{ "a" : "T", "q" : "Las huellas dactilares de los hijos se parecen a las de sus padres." },
{ "a" : "T", "q" : "Nacemos con 300 huesos pero de adultos sólo tenemos 206." },
{ "a" : "T", "q" : "Tomar un vaso de agua fría quema aproximadamente 60 calorías." },
{ "a" : "T", "q" : "Shakespeare y Cervantes murieron el mismo día." },
{ "a" : "T", "q" : "La cucaracha tiene dos cerebros, uno en la cabeza y en su cola." },
{ "a" : "T", "q" : "Los cascos vikingos tenían cuernos." },
{ "a" : "T", "q" : "Las arañas son insectos de ocho patas." },
{ "a" : "T", "q" : "El guepardo es el único felino en el mundo que no tiene garras retráctiles." },
{ "a" : "T", "q" : "Las caras opuestas de un dado siempre suman 8." },
{ "a" : "T", "q" : "En la cara oculta de la luna es siempre de noche." },
{ "a" : "T", "q" : "Las cebras son negras con rallas blancas." },
{ "a" : "T", "q" : "Los delfines son los animales más inteligentes después de los humanos." },
{ "a" : "T", "q" : "En el siglo XIX, en Inglaterra, el intento de suicidio era castigado con pena de muerte." },
{ "a" : "T", "q" : "Cada día producimos más de un litro de saliva." },
{ "a" : "T", "q" : "Las personas diestras viven más que las zurdas." },
{ "a" : "T", "q" : "Los caballos corren más rápido que los cocodrilos." },
{ "a" : "T", "q" : "Los delfines duermen con un ojo abierto." },
{ "a" : "T", "q" : "Si toda la población china saltara a la vez, la tierra se desplazaría 1mm de su órbita." },
{ "a" : "T", "q" : "Se conocen más de 10 billones de decimales del número PI." },
{ "a" : "T", "q" : "Cuando muere una abeja reina, toda la colmena desaparece." },
{ "a" : "T", "q" : "Los relojes con números romanos muestran el número 4 como IIII en lugar de IV." },
{ "a" : "T", "q" : "Todos los peces payaso nacen hembras." },
